-- Generated by scripts/generate-seed-sql.mjs from src/data/seed.json — do not edit by hand.
-- Run after schema.sql. Safe to re-run: it wipes and re-inserts the catalogue.

delete from public.menu_items;
delete from public.restaurants;

with r as (
  insert into public.restaurants (slug, name, cuisine_tags, rating, rating_count, delivery_min_minutes, delivery_max_minutes, is_veg_only, area, lat, lng)
  values ('biryani-junction', 'Biryani Junction', array['Biryani', 'Hyderabadi', 'Mughlai']::text[], 4.5, 2310, 30, 40, false, 'Banjara Hills', 17.4106, 78.4382)
  returning id
)
insert into public.menu_items (restaurant_id, name, price_minor, is_veg, is_featured, sort_order, image_url)
select r.id, m.* from r, (values
  ('Chicken Dum Biryani', 32000, false, true, 0, 'https://loremflickr.com/640/480/biryani?lock=7'),
  ('Veg Dum Biryani', 24000, true, true, 1, 'https://loremflickr.com/640/480/biryani,rice?lock=14'),
  ('Mutton Biryani', 39000, false, false, 2, 'https://loremflickr.com/640/480/mutton?lock=21'),
  ('Paneer 65', 22000, true, false, 3, 'https://loremflickr.com/640/480/paneer?lock=28')
) as m(name, price_minor, is_veg, is_featured, sort_order, image_url);

with r as (
  insert into public.restaurants (slug, name, cuisine_tags, rating, rating_count, delivery_min_minutes, delivery_max_minutes, is_veg_only, area, lat, lng)
  values ('sattvik-bhojanalaya', 'Sattvik Bhojanalaya', array['North Indian', 'Thali', 'Rajasthani']::text[], 4.7, 1840, 25, 35, true, 'Jubilee Hills', 17.4315, 78.408)
  returning id
)
insert into public.menu_items (restaurant_id, name, price_minor, is_veg, is_featured, sort_order, image_url)
select r.id, m.* from r, (values
  ('Rajasthani Thali', 28000, true, true, 0, 'https://loremflickr.com/640/480/thali?lock=35'),
  ('Dal Baati Churma', 22000, true, false, 1, 'https://loremflickr.com/640/480/lentils?lock=42'),
  ('Gatte ki Sabzi', 18000, true, false, 2, 'https://loremflickr.com/640/480/curry?lock=49')
) as m(name, price_minor, is_veg, is_featured, sort_order, image_url);

with r as (
  insert into public.restaurants (slug, name, cuisine_tags, rating, rating_count, delivery_min_minutes, delivery_max_minutes, is_veg_only, area, lat, lng)
  values ('dosa-corner', 'Dosa Corner', array['South Indian', 'Breakfast', 'Tiffins']::text[], 4.3, 5120, 20, 30, true, 'Madhapur', 17.4513, 78.3894)
  returning id
)
insert into public.menu_items (restaurant_id, name, price_minor, is_veg, is_featured, sort_order, image_url)
select r.id, m.* from r, (values
  ('Ghee Podi Masala Dosa', 14000, true, true, 0, 'https://loremflickr.com/640/480/dosa?lock=56'),
  ('Idli Sambar', 9000, true, false, 1, 'https://loremflickr.com/640/480/idli?lock=63'),
  ('Filter Coffee', 6000, true, false, 2, 'https://loremflickr.com/640/480/coffee?lock=70')
) as m(name, price_minor, is_veg, is_featured, sort_order, image_url);

with r as (
  insert into public.restaurants (slug, name, cuisine_tags, rating, rating_count, delivery_min_minutes, delivery_max_minutes, is_veg_only, area, lat, lng)
  values ('wok-and-roll', 'Wok & Roll', array['Chinese', 'Asian', 'Indo-Chinese']::text[], 4.1, 980, 35, 45, false, 'Gachibowli', 17.4361, 78.3517)
  returning id
)
insert into public.menu_items (restaurant_id, name, price_minor, is_veg, is_featured, sort_order, image_url)
select r.id, m.* from r, (values
  ('Chicken Hakka Noodles', 21000, false, true, 0, 'https://loremflickr.com/640/480/noodles?lock=77'),
  ('Veg Manchurian', 18000, true, true, 1, 'https://loremflickr.com/640/480/manchurian?lock=84'),
  ('Veg Fried Rice', 17000, true, false, 2, 'https://loremflickr.com/640/480/friedrice?lock=91'),
  ('Chilli Chicken', 24000, false, false, 3, 'https://loremflickr.com/640/480/chicken?lock=98')
) as m(name, price_minor, is_veg, is_featured, sort_order, image_url);

with r as (
  insert into public.restaurants (slug, name, cuisine_tags, rating, rating_count, delivery_min_minutes, delivery_max_minutes, is_veg_only, area, lat, lng)
  values ('nonnas-pizzeria', 'Nonna''s Pizzeria', array['Pizza', 'Italian']::text[], 4.4, 1560, 30, 40, false, 'Kondapur', 17.4622, 78.3568)
  returning id
)
insert into public.menu_items (restaurant_id, name, price_minor, is_veg, is_featured, sort_order, image_url)
select r.id, m.* from r, (values
  ('Pepperoni Pizza', 45000, false, true, 0, 'https://loremflickr.com/640/480/pepperoni?lock=105'),
  ('Margherita Pizza', 35000, true, true, 1, 'https://loremflickr.com/640/480/margherita?lock=112'),
  ('Garlic Bread', 15000, true, false, 2, 'https://loremflickr.com/640/480/garlicbread?lock=119')
) as m(name, price_minor, is_veg, is_featured, sort_order, image_url);

with r as (
  insert into public.restaurants (slug, name, cuisine_tags, rating, rating_count, delivery_min_minutes, delivery_max_minutes, is_veg_only, area, lat, lng)
  values ('burger-barracks', 'Burger Barracks', array['Burgers', 'Fast Food', 'American']::text[], 4, 3200, 20, 30, false, 'Hitech City', 17.4475, 78.3744)
  returning id
)
insert into public.menu_items (restaurant_id, name, price_minor, is_veg, is_featured, sort_order, image_url)
select r.id, m.* from r, (values
  ('Double Smash Burger', 29000, false, true, 0, 'https://loremflickr.com/640/480/burger?lock=126'),
  ('Crispy Paneer Burger', 22000, true, true, 1, 'https://loremflickr.com/640/480/veggieburger?lock=133'),
  ('Loaded Fries', 16000, true, false, 2, 'https://loremflickr.com/640/480/fries?lock=140')
) as m(name, price_minor, is_veg, is_featured, sort_order, image_url);

with r as (
  insert into public.restaurants (slug, name, cuisine_tags, rating, rating_count, delivery_min_minutes, delivery_max_minutes, is_veg_only, area, lat, lng)
  values ('the-green-bowl', 'The Green Bowl', array['Salads', 'Healthy', 'Bowls']::text[], 4.6, 720, 25, 35, true, 'Jubilee Hills', 17.4295, 78.4094)
  returning id
)
insert into public.menu_items (restaurant_id, name, price_minor, is_veg, is_featured, sort_order, image_url)
select r.id, m.* from r, (values
  ('Buddha Bowl', 32000, true, true, 0, 'https://loremflickr.com/640/480/buddhabowl?lock=147'),
  ('Quinoa Salad', 28000, true, false, 1, 'https://loremflickr.com/640/480/salad?lock=154'),
  ('Cold-Pressed Juice', 15000, true, false, 2, 'https://loremflickr.com/640/480/juice?lock=161')
) as m(name, price_minor, is_veg, is_featured, sort_order, image_url);

with r as (
  insert into public.restaurants (slug, name, cuisine_tags, rating, rating_count, delivery_min_minutes, delivery_max_minutes, is_veg_only, area, lat, lng)
  values ('kebab-kingdom', 'Kebab Kingdom', array['Kebabs', 'Mughlai', 'Grill']::text[], 4.2, 1120, 35, 50, false, 'Tolichowki', 17.4019, 78.4138)
  returning id
)
insert into public.menu_items (restaurant_id, name, price_minor, is_veg, is_featured, sort_order, image_url)
select r.id, m.* from r, (values
  ('Seekh Kebab Platter', 38000, false, true, 0, 'https://loremflickr.com/640/480/kebab?lock=168'),
  ('Hara Bhara Kebab', 22000, true, true, 1, 'https://loremflickr.com/640/480/vegkebab?lock=175'),
  ('Chicken Tikka', 30000, false, false, 2, 'https://loremflickr.com/640/480/tikka?lock=182')
) as m(name, price_minor, is_veg, is_featured, sort_order, image_url);

with r as (
  insert into public.restaurants (slug, name, cuisine_tags, rating, rating_count, delivery_min_minutes, delivery_max_minutes, is_veg_only, area, lat, lng)
  values ('chai-and-chaat', 'Chai & Chaat', array['Street Food', 'Chaat', 'Snacks']::text[], 4.4, 4410, 15, 25, true, 'Ameerpet', 17.4425, 78.4448)
  returning id
)
insert into public.menu_items (restaurant_id, name, price_minor, is_veg, is_featured, sort_order, image_url)
select r.id, m.* from r, (values
  ('Pani Puri', 8000, true, true, 0, 'https://loremflickr.com/640/480/panipuri?lock=189'),
  ('Dahi Bhalla', 11000, true, false, 1, 'https://loremflickr.com/640/480/chaat?lock=196'),
  ('Masala Chai', 4000, true, false, 2, 'https://loremflickr.com/640/480/chai?lock=203')
) as m(name, price_minor, is_veg, is_featured, sort_order, image_url);

with r as (
  insert into public.restaurants (slug, name, cuisine_tags, rating, rating_count, delivery_min_minutes, delivery_max_minutes, is_veg_only, area, lat, lng)
  values ('sushi-sora', 'Sushi Sora', array['Japanese', 'Sushi', 'Asian']::text[], 4.6, 410, 40, 55, false, 'Banjara Hills', 17.4136, 78.4361)
  returning id
)
insert into public.menu_items (restaurant_id, name, price_minor, is_veg, is_featured, sort_order, image_url)
select r.id, m.* from r, (values
  ('Salmon Nigiri', 62000, false, true, 0, 'https://loremflickr.com/640/480/sushi?lock=210'),
  ('Avocado Maki', 42000, true, true, 1, 'https://loremflickr.com/640/480/maki?lock=217'),
  ('Miso Soup', 18000, true, false, 2, 'https://loremflickr.com/640/480/miso?lock=224')
) as m(name, price_minor, is_veg, is_featured, sort_order, image_url);

with r as (
  insert into public.restaurants (slug, name, cuisine_tags, rating, rating_count, delivery_min_minutes, delivery_max_minutes, is_veg_only, area, lat, lng)
  values ('punjabi-dhaba', 'Punjabi Dhaba', array['North Indian', 'Punjabi', 'Curry']::text[], 4.3, 2780, 30, 40, false, 'Kukatpally', 17.4869, 78.4124)
  returning id
)
insert into public.menu_items (restaurant_id, name, price_minor, is_veg, is_featured, sort_order, image_url)
select r.id, m.* from r, (values
  ('Butter Chicken', 34000, false, true, 0, 'https://loremflickr.com/640/480/butterchicken?lock=231'),
  ('Dal Makhani', 22000, true, true, 1, 'https://loremflickr.com/640/480/lentils?lock=238'),
  ('Butter Naan', 5000, true, false, 2, 'https://loremflickr.com/640/480/naan?lock=245')
) as m(name, price_minor, is_veg, is_featured, sort_order, image_url);

with r as (
  insert into public.restaurants (slug, name, cuisine_tags, rating, rating_count, delivery_min_minutes, delivery_max_minutes, is_veg_only, area, lat, lng)
  values ('sweet-tooth', 'Sweet Tooth', array['Desserts', 'Bakery', 'Ice Cream']::text[], 4.8, 1290, 20, 30, true, 'Madhapur', 17.4433, 78.395)
  returning id
)
insert into public.menu_items (restaurant_id, name, price_minor, is_veg, is_featured, sort_order, image_url)
select r.id, m.* from r, (values
  ('Chocolate Lava Cake', 19000, true, true, 0, 'https://loremflickr.com/640/480/lavacake?lock=252'),
  ('Blueberry Cheesecake', 24000, true, false, 1, 'https://loremflickr.com/640/480/cheesecake?lock=259'),
  ('Gulab Jamun', 9000, true, false, 2, 'https://loremflickr.com/640/480/gulabjamun?lock=266')
) as m(name, price_minor, is_veg, is_featured, sort_order, image_url);

with r as (
  insert into public.restaurants (slug, name, cuisine_tags, rating, rating_count, delivery_min_minutes, delivery_max_minutes, is_veg_only, area, lat, lng)
  values ('taco-loco', 'Taco Loco', array['Mexican', 'Tacos', 'Burritos']::text[], 4.1, 640, 30, 45, false, 'Gachibowli', 17.4391, 78.3496)
  returning id
)
insert into public.menu_items (restaurant_id, name, price_minor, is_veg, is_featured, sort_order, image_url)
select r.id, m.* from r, (values
  ('Carnitas Tacos', 33000, false, true, 0, 'https://loremflickr.com/640/480/tacos?lock=273'),
  ('Bean & Cheese Burrito', 27000, true, true, 1, 'https://loremflickr.com/640/480/burrito?lock=280'),
  ('Nachos Grande', 21000, true, false, 2, 'https://loremflickr.com/640/480/nachos?lock=287')
) as m(name, price_minor, is_veg, is_featured, sort_order, image_url);

with r as (
  insert into public.restaurants (slug, name, cuisine_tags, rating, rating_count, delivery_min_minutes, delivery_max_minutes, is_veg_only, area, lat, lng)
  values ('coastal-catch', 'Coastal Catch', array['Seafood', 'Mangalorean', 'Coastal']::text[], 4.5, 860, 40, 55, false, 'Somajiguda', 17.4269, 78.4574)
  returning id
)
insert into public.menu_items (restaurant_id, name, price_minor, is_veg, is_featured, sort_order, image_url)
select r.id, m.* from r, (values
  ('Mangalorean Fish Curry', 41000, false, true, 0, 'https://loremflickr.com/640/480/fishcurry?lock=294'),
  ('Prawn Ghee Roast', 48000, false, false, 1, 'https://loremflickr.com/640/480/prawns?lock=301'),
  ('Crab Masala', 56000, false, false, 2, 'https://loremflickr.com/640/480/crab?lock=308')
) as m(name, price_minor, is_veg, is_featured, sort_order, image_url);

with r as (
  insert into public.restaurants (slug, name, cuisine_tags, rating, rating_count, delivery_min_minutes, delivery_max_minutes, is_veg_only, area, lat, lng)
  values ('momo-station', 'Momo Station', array['Tibetan', 'Nepali', 'Momos']::text[], 4.2, 1930, 20, 30, false, 'Ameerpet', 17.4335, 78.4511)
  returning id
)
insert into public.menu_items (restaurant_id, name, price_minor, is_veg, is_featured, sort_order, image_url)
select r.id, m.* from r, (values
  ('Chicken Steam Momos', 16000, false, true, 0, 'https://loremflickr.com/640/480/momos?lock=315'),
  ('Veg Fried Momos', 14000, true, true, 1, 'https://loremflickr.com/640/480/dumplings?lock=322'),
  ('Thukpa', 18000, true, false, 2, 'https://loremflickr.com/640/480/thukpa?lock=329')
) as m(name, price_minor, is_veg, is_featured, sort_order, image_url);

with r as (
  insert into public.restaurants (slug, name, cuisine_tags, rating, rating_count, delivery_min_minutes, delivery_max_minutes, is_veg_only, area, lat, lng)
  values ('dilli-paratha-house', 'Dilli Paratha House', array['North Indian', 'Breakfast', 'Parathas']::text[], 4.4, 2210, 20, 30, true, 'Kukatpally', 17.4849, 78.4138)
  returning id
)
insert into public.menu_items (restaurant_id, name, price_minor, is_veg, is_featured, sort_order, image_url)
select r.id, m.* from r, (values
  ('Aloo Paratha with Makhan', 12000, true, true, 0, 'https://loremflickr.com/640/480/paratha?lock=336'),
  ('Paneer Paratha', 15000, true, false, 1, 'https://loremflickr.com/640/480/paneer?lock=343'),
  ('Lassi', 7000, true, false, 2, 'https://loremflickr.com/640/480/lassi?lock=350')
) as m(name, price_minor, is_veg, is_featured, sort_order, image_url);

